# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e9ded9c8aa374d0033b923efc096dc041bb8948ff562ae8f8976a83e37fe7f5b5dbb7fff08ee13cf092a653d4a21b6d0ea41f06bd90945dd67815990b3f8b6e5

test:
  secret_key_base: 984ec90315aa356d8cfb8898a97eb3928a205da5e85b5c194f682ded5a5dbf356c7ebf5cc6e403a4fbfd686c5f364a4b6420878d0db48238c8b31d0860105c20

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
